spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medico_db  # comme dans docker-compose
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: lab-frontend
            client-secret: Yj2ZW8heLdKdxW5MTMX33Z4seljBFPXe
            authorization-grant-type: authorization_code
            # => IMPORTANT : laisser Spring calculer {baseUrl}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            # pas de / final, doit matcher exactement l'issuer du realm
            issuer-uri: http://localhost:8180/realms/medico-cloud

minio:
  url: http://localhost:9000
  access-key: minioadmin       # comme docker-compose
  secret-key: minioadmin       # comme docker-compose
  bucket: lab-reports

logging:
  level:
    root: INFO
